CntoDev/compositions

reference-adaptations/Night%20Gear/header.sqe, reference-adaptations/TFN%20Desert/header.sqe, reference-adaptations/TFN%20Forest/header.sqe, reference-adaptations/TFN%20Grassland/header.sqe, reference-adaptations/TFN%20Jungle/header.sqe, reference-adaptations/TFN%20Snow/header.sqe, reference-adaptations/US%20Urban/header.sqe, reference/Default%20Modules%20(Coop)/header.sqe, reference/Default%20Modules%20(PvP)/header.sqe, reference/GMs/header.sqe, reference/Russian%20Army/header.sqe, reference/Scopebox/header.sqe, reference/Task%20Force%20Noctem%20Vehicles/header.sqe, reference/Task%20Force%20Noctem/header.sqe, reference/US%20Army/header.sqe, reference/VISCOM/header.sqe
Assigned compositions to new CNTO subcategories.
=> assigned compositions to new subcategories

reference/Default%20Modules%20(Coop)/composition.sqe
Added the JTAC Report and procedure to the CNTO TTP's.
=> CNTO TTP's JTAC Report added

reference-adaptations/US%20Urban/composition.sqe
Fixes wrong backpacks for US urban adaptation.
=> fixed wrong backpacks for US urban

reference-adaptations/JTAC/composition.sqe, reference-adaptations/JTAC/header.sqe, reference-adaptations/UAV%20OP_1/composition.sqe, reference-adaptations/UAV%20OP_1/header.sqe, reference-adaptations/US%20Urban/composition.sqe, reference/Default%20Modules%20(Coop)/composition.sqe, reference/Task%20Force%20Noctem/composition.sqe
Several Updates and Additions detailed below.
1. Added JTAC Adaptation Module.
2. Added UAV OP Adaptation Module.
3. Updated US Urban Adaptation Module with correct backpacks.
4. Updated TFN Faction Composition correcting ENGR Leads Helmet/Vest.
5. Updated Version of TFN in line with changes.
6. Updated Version of Coop Default Modules in line with TTP changes.
Please review and merge at your earliest opportunity.
Regards,
Dachi
=> Development Updates to Master

Dachi/Misc Compositions/RUS%20Large%20Air%20Drop%20Resupply/composition.sqe, Dachi/Misc Compositions/RUS%20Large%20Air%20Drop%20Resupply/header.sqe, Dachi/Misc Compositions/Task%20Force%20Noctem%20Vehicles/composition.sqe, Dachi/Misc Compositions/Task%20Force%20Noctem%20Vehicles/header.sqe, Dachi/Misc Compositions/US%20Large%20Air%20Drop%20Resupply/composition.sqe, Dachi/Misc Compositions/US%20Large%20Air%20Drop%20Resupply/header.sqe
All Faction Large Crate Resupply Modules
=> All Faction Large Crate Resupply Modules

reference/Default%20Modules%20(Coop)/composition.sqe
Setting has been changed from "Amount based on ammo" to "Entire Magazine".
=> ACE Rearm Setting Changed

reference/Default%20Modules%20(Coop)/composition.sqe
=> bumped to 1.06

reference/CHANGELOG.md, reference/Russian%20Army/composition.sqe, reference/Task%20Force%20Noctem/composition.sqe, reference/US%20Army/composition.sqe
Overhauled all standard factions
=> Updating standard factions

reference/Russian%20Army/composition.sqe
Arba's changes, squashed together to not include US/RU composition swap.
=> Fixed persistant callsigns for RU Army

reference/Russian%20Army/composition.sqe, reference/Task%20Force%20Noctem/composition.sqe, reference/US%20Army/composition.sqe
The clean diff against 27e2f6dc0d is on https://pastebin.com/M3q1yNd5.
=> Edited the new code to more resemble the old one

reference/Russian%20Army/composition.sqe, reference/Task%20Force%20Noctem/composition.sqe, reference/US%20Army/composition.sqe
Faction versions updated to v1.09
=> Versions Updated

reference/CHANGELOG.md, reference/Russian%20Army/composition.sqe, reference/Task%20Force%20Noctem/composition.sqe, reference/US%20Army/composition.sqe
Changed Medic loadouts in all factions:
From: 6 x 1000ml Blood Bags
changed
To : 2 x 1000ml and 8 x 500ml blood bags
Updated the changelog to show updated faction versions and the changes made.
=> Dachi patch 2

Russian%20Army/composition.sqe, Russian%20Army/header.sqe, US%20Army/composition.sqe, US%20Army/header.sqe
FIxed AAR's carrying both V40 mini and M67 Frag. Now carrying correctly 4x M67 Frag
=> RUS + US Hotfix

reference/CHANGELOG.md, reference/Task%20Force%20Noctem/composition.sqe, reference/US%20Army/composition.sqe
Updated US and TFN factions with Bipods for M249 and removed M14 magazines from US DMT
=> Factions V1.13.3

Approved Custom Factions/README.md, Approved Custom Factions/USMC_Recon-V1.08/composition.sqe, Approved Custom Factions/USMC_Recon-V1.08/header.sqe, Approved Custom Factions/US_Rangers-V1.10/composition.sqe, Approved Custom Factions/US_Rangers-V1.10/header.sqe
This is a folder to store already approved custom factions. This will enable older custom factions to be updated for re-use.
=> Created Custom Faction Folder

Approved Custom Factions/Future%20Crew/composition.sqe, Approved Custom Factions/Future%20Crew/header.sqe, Approved Custom Factions/Task%20Force%20Nivalis%20v2/composition.sqe, Approved Custom Factions/Task%20Force%20Nivalis%20v2/header.sqe, Approved Custom Factions/Task_Force_Nivalis-V1.13.6/header.sqe
Task Force Nivalis
Removed GPS, Bluforce Tracking, Radios from some roles on Task Force Nivalis.
=> Updated TF Nivalis, added Future Crew

reference/PMC%20Faction/composition.sqe, reference/PMC%20Faction/header.sqe
Hi Dachi, I found several problems with the faction but I fixed all of them (see my commit).
Problems found & fixed:
- Your weapon selector still didn't work for me, I'm not sure why as the script looked fine but I changed how the condition works and now it works for me 100% of the time. It functions exactly the same for the end user.
- DMT weapon selector had "I_sniper_F" instead of "I_Sniper_F" which is case senstive and so didn't work.
- East faction DMT Sniper was the wrong class and so could not select a weapon.
- DMT lost their scope when selecting a weapon and couldn't get it back. I fixed this by adding an if-check to see if they had any attachments and instructing them to remove the attachment to continue.
- Multiple duplicate respawn, resupply markers and weapon selector markers …
=> Seb review of PMC faction

reference/PMC%20Faction/composition.sqe, reference/PMC%20Faction/header.sqe
Addition of the PMC faction as a 4th faction for mission makers to use.
=> 4th PMC Faction

Approved Custom Factions/Delta%20Force%201990/composition.sqe, Approved Custom Factions/Delta%20Force%201990/header.sqe, Approved Custom Factions/Future%20Crew/composition.sqe, Approved Custom Factions/Soviet%20Army%201985/composition.sqe, Approved Custom Factions/Soviet%20Army%201985/header.sqe, Approved Custom Factions/Task%20Force%20Nivalis%20v2/composition.sqe, Approved Custom Factions/USMC_Recon-V1.08/composition.sqe, Approved Custom Factions/US_Rangers-V1.10/composition.sqe
Also added:
Delta Force 1990
Soviet Army 1985
(these are not yet approved but should be by the time this branch is merged)
I also fixed USMC_Recon and US_Rangers for you Dachi ;)
Obv wait on approving this Pull request until Arma-Additions updates.
=> Updated all approved custom factions from A3EE to A3AA

Approved Custom Factions/Vietnam%20US%20Army/composition.sqe, Approved Custom Factions/Vietnam%20US%20Army/header.sqe
Custom Faction reviewed and approved via the forums: https://www.carpenoctem.co/forums/m/26081621/viewthread/33297518-vietnam-us-army-1970ies
This custom faction composition is based on v1.14.2 of our Standard Factions.
=> Vietnam US Army Faction

Approved Custom Factions/Vietnam%20ARVN/composition.sqe, Approved Custom Factions/Vietnam%20ARVN/header.sqe
https://www.carpenoctem.co/forums/m/26081621/viewthread/33306453-vietnam-arvn-1963/page/1
=> Initial Upload Vietnam ARVN (1963)

reference/PMC%20Faction/composition.sqe, reference/Russian%20Army/composition.sqe, reference/Task%20Force%20Noctem/composition.sqe, reference/US%20Army/composition.sqe
Pull Request Change Log:
- Disabled BFT on GM: fixes #136
- Added Asssault Pack to pilot including Toolkit, checked that ACE3 Option "is Engineer" is active: fixes #124
- Added 4x cargo slings to helo pilot and co-pilot: fixes #129
- Removed AN/PCR-148 from PLT Sergeant: fixes #116
- Added Scopebox and VISCOM to Standard Faction composition: fixes #80
=> v1.14.3 Update

reference/Russian%20Army/composition.sqe, reference/Russian%20Army/header.sqe, reference/Task%20Force%20Noctem/composition.sqe, reference/Task%20Force%20Noctem/header.sqe, reference/US%20Army/composition.sqe, reference/US%20Army/header.sqe
- CHANGED composition version from v3.0.0 to v3.0.1
- CHANGED soldier group order of Charlie squad. fixes #202
- CHANGED composition version from v3.0.0 to v3.0.1
- CHANGED GM uniform from `rhs_uniform_m88_patchless` to `rhs_uniform_afghanka`. fixes #199
- CHANGED composition version from v3.0.0 to v3.0.1
No balance changes, only minor bug fixes and version updates. Thus this PR only requires one successful review for roll-out.
=> v3.0.1 - Standard Faction Composition Fixes
